const $=s=>document.querySelector(s),lobby=$('#lobby'),game=$('#game'),canvas=$('#gameCanvas'),ctx=canvas.getContext('2d'),mini=$('#miniCanvas'),mctx=mini.getContext('2d');
const nameInput=$('#snakeName'),colorInput=$('#snakeColor'),startButton=$('#startButton'),music=$('#music'),eatSound=$('#eatSound');
const WORLD=5200,WORLD_CENTER=WORLD/2,WORLD_RADIUS=WORLD/2-45,ORB_COUNT=420,CRYSTAL_COUNT=8,BOT_COUNT=20,BASE_SPEED=125,orbColors=['#ff3cb4','#ff3f52','#48c9ff','#ffffff','#ffe34d'];
const botNames=['Чечня на связи','Щас спросим с тебя','Шустрый пельмень','Укус судьбы','Змей Горыныч','Не тормози','Колбаса в пути','Опасный тапок','Съел и ушёл','Борщ летит','Хвост трубой','Дядя Удав','Грозный шнурок','Ползи отсюда','Кусь за Русь','Сфера моя','Не догоняй','Кобра добра','Червяк босс','Анаконда 2007','Лютый огурец','Где мои очки'];
let player,bots=[],orbs=[],crystals=[],crystalTotal=Number(localStorage.getItem('snakeCrystals')||0),running=false,paused=false,last=0,mouse={x:innerWidth/2,y:innerHeight/2},boost=false,boostClock=0,respawns=[],leaderClock=0,onlineSocket=null,onlineId='',networkClock=0;

$('#bestScore').textContent=localStorage.getItem('snakeBestScore')||'0';eatSound.volume=.5;music.volume=.7;
for(let i=0;i<15;i++){const o=document.createElement('i'),size=10+Math.random()*26;o.className='orb';[['--size',size+'px'],['--x',Math.random()*96+'%'],['--y',Math.random()*94+'%'],['--dx',-60+Math.random()*120+'px'],['--dy',-55+Math.random()*110+'px'],['--duration',5+Math.random()*6+'s'],['--delay',-Math.random()*8+'s'],['--color',orbColors[i%5]]].forEach(v=>o.style.setProperty(...v));$('#floatingOrbs').append(o)}
nameInput.addEventListener('input',()=>startButton.disabled=!nameInput.value.trim());
addEventListener('resize',resize);addEventListener('mousemove',e=>mouse={x:e.clientX,y:e.clientY});addEventListener('mousedown',e=>{if(e.button===0)boost=true});addEventListener('mouseup',e=>{if(e.button===0)boost=false});
addEventListener('keydown',e=>{if(e.key==='Escape'&&running)togglePause()});$('#continueButton').onclick=togglePause;startButton.onclick=()=>start(false);$('#retryButton').onclick=()=>start(true);$('#lobbyButton').onclick=toLobby;

function resize(){canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio;canvas.style.width=innerWidth+'px';canvas.style.height=innerHeight+'px';ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}resize();
function rnd(a,b){return a+Math.random()*(b-a)}function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}function circlePoint(margin=250){const a=rnd(0,Math.PI*2),r=Math.sqrt(Math.random())*(WORLD_RADIUS-margin);return{x:WORLD_CENTER+Math.cos(a)*r,y:WORLD_CENTER+Math.sin(a)*r}}function safePoint(){for(let n=0;n<100;n++){const p=circlePoint(280);if([player,...bots].filter(Boolean).every(s=>dist(p,s)>280))return p}return{x:WORLD_CENTER,y:WORLD_CENTER}}
function makeSnake(name,color,isBot=false){const p=safePoint(),angle=rnd(0,Math.PI*2),s={name,color,isBot,x:p.x,y:p.y,angle,targetAngle:angle,score:0,alive:true,shield:2,trail:[],segments:3,visualSegments:3,aiClock:0,attacking:false,wiggle:rnd(0,Math.PI*2)};for(let i=0;i<80;i++)s.trail.push({x:s.x-Math.cos(angle)*i*4,y:s.y-Math.sin(angle)*i*4});return s}
function makeOrb(x,y,large=false){if(x===undefined||y===undefined)({x,y}=circlePoint(180));const r=Math.random(),size=large?3:r<.5?1:r<.8?2:3;return{x,y,size,color:orbColors[Math.floor(Math.random()*5)],value:size===1?10:size===2?25:50,radius:size===1?5:size===2?8:12}}
function makeCrystal(){const p=circlePoint(260);return{x:p.x,y:p.y,phase:rnd(0,Math.PI*2)}}
function serverAddress(){const fromUrl=new URLSearchParams(location.search).get('server');if(fromUrl)return fromUrl;if(location.protocol==='http:'||location.protocol==='https:')return`${location.protocol==='https:'?'wss':'ws'}://${location.host}`;return'ws://localhost:8080'}
function connectOnline(name,color){if(onlineSocket)onlineSocket.close();onlineSocket=new WebSocket(serverAddress());onlineSocket.onopen=()=>onlineSocket.send(JSON.stringify({type:'join',name,color}));onlineSocket.onmessage=event=>{let message;try{message=JSON.parse(event.data)}catch{return}if(message.type==='welcome'){onlineId=message.id;return}if(message.type!=='state'||!player)return;const seen=new Set();for(const data of message.players){if(data.id===onlineId){player.x+=(data.x-player.x)*.28;player.y+=(data.y-player.y)*.28;player.angle=data.angle;player.score=data.score;if(!data.alive&&player.alive)kill(player);continue}seen.add(data.id);let snake=bots.find(item=>item.onlineId===data.id);if(!snake){snake=makeSnake(data.name,data.color,true);snake.onlineId=data.id;snake.shield=0;bots.push(snake)}if(!snake.alive&&data.alive){snake.trail=[];snake.visualSegments=3}addTrailDistanceBased(snake,data.x,data.y);snake.x=data.x;snake.y=data.y;snake.angle=data.angle;snake.targetAngle=data.angle;snake.score=data.score;snake.visualSegments+=(3+Math.floor(data.score/25)-snake.visualSegments)*.12;snake.segments=snake.visualSegments;if(snake.alive&&!data.alive)dropExperience(snake);snake.alive=data.alive}bots=bots.filter(item=>!item.onlineId||seen.has(item.onlineId))};onlineSocket.onclose=()=>{onlineSocket=null}}
function start(retry){const name=retry?localStorage.getItem('snakeName'):nameInput.value.trim(),color=retry?localStorage.getItem('snakeColor'):colorInput.value;if(!name)return;if(!retry){localStorage.setItem('snakeName',name);localStorage.setItem('snakeColor',color)}lobby.classList.add('hidden');game.classList.remove('hidden');$('#resultOverlay').classList.add('hidden');$('#pauseOverlay').classList.add('hidden');orbs=Array.from({length:ORB_COUNT},()=>makeOrb());crystals=Array.from({length:CRYSTAL_COUNT},()=>makeCrystal());$('#crystalCount').textContent=crystalTotal;bots=[];player=null;player=makeSnake(name,color);connectOnline(name,color);respawns=[];paused=false;running=true;last=performance.now();music.currentTime=0;music.play().catch(()=>{});requestAnimationFrame(loop)}
function toLobby(){running=false;if(onlineSocket)onlineSocket.close();music.pause();game.classList.add('hidden');lobby.classList.remove('hidden');$('#bestScore').textContent=localStorage.getItem('snakeBestScore')||'0'}
function togglePause(){if(!player?.alive)return;paused=!paused;$('#pauseOverlay').classList.toggle('hidden',!paused);if(paused)music.pause();else{music.play().catch(()=>{});last=performance.now()}}
function angleDiff(a,b){return Math.atan2(Math.sin(b-a),Math.cos(b-a))}function turn(s,target,dt){s.angle+=Math.max(-2.7*dt,Math.min(2.7*dt,angleDiff(s.angle,target)))}
function addTrailDistanceBased(s,newX,newY){const prev=s.trail[0]||{x:s.x,y:s.y},dx=newX-prev.x,dy=newY-prev.y,d=Math.hypot(dx,dy),spacing=4;if(d<spacing)return;const steps=Math.floor(d/spacing);for(let i=1;i<=steps;i++){const travel=Math.min(i*spacing,d),t=travel/d;s.trail.unshift({x:prev.x+dx*t,y:prev.y+dy*t})}}
function updateSnake(s,dt){if(!s.alive)return;s.shield=Math.max(0,s.shield-dt);s.wiggle+=dt*3.5;let fast=false;if(s.isBot){s.aiClock-=dt;if(s.aiClock<=0){s.aiClock=rnd(.35,1.1);const danger=[player,...bots].filter(o=>o&&o!==s&&o.alive&&dist(s,o)<300);if(danger.length&&Math.random()<1/3){const t=danger[0];s.targetAngle=Math.atan2(t.y-s.y,t.x-s.x)+rnd(-.45,.45);s.attacking=true}else{const nearest=orbs.reduce((a,o)=>dist(s,o)<dist(s,a)?o:a,orbs[0]);s.targetAngle=nearest?Math.atan2(nearest.y-s.y,nearest.x-s.x):s.angle+rnd(-1,1);s.attacking=false}}fast=s.score>=5&&(s.attacking||Math.random()<.008)}else{s.targetAngle=Math.atan2(mouse.y-innerHeight/2,mouse.x-innerWidth/2);fast=boost&&s.score>=5&&s.shield<=0}turn(s,s.targetAngle,dt);if(fast){s._boost=(s._boost||0)+dt;while(s._boost>=.5){s._boost-=.5;s.score=Math.max(0,s.score-5)}}const speed=BASE_SPEED*(fast?2:1),newX=s.x+Math.cos(s.angle)*speed*dt,newY=s.y+Math.sin(s.angle)*speed*dt;addTrailDistanceBased(s,newX,newY);s.x=newX;s.y=newY;const wanted=3+Math.floor(s.score/25),growthSpeed=.48;s.visualSegments+=Math.max(-growthSpeed*dt,Math.min(growthSpeed*dt,wanted-s.visualSegments));s.segments=Math.max(3,s.visualSegments);const maxTrail=Math.ceil(s.visualSegments)*9+30;if(s.trail.length>maxTrail)s.trail.length=maxTrail;if(Math.hypot(s.x-WORLD_CENTER,s.y-WORLD_CENTER)>WORLD_RADIUS-20)kill(s);if(s.shield<=0)collect(s)}
function collect(s){for(let i=orbs.length-1;i>=0;i--){const o=orbs[i];if(Math.hypot(s.x-o.x,s.y-o.y)<20+o.radius){if(!s.isBot&&onlineSocket?.readyState===WebSocket.OPEN)onlineSocket.send(JSON.stringify({type:'eat',value:o.value}));else s.score+=o.value;orbs.splice(i,1);orbs.push(makeOrb());if(!s.isBot){eatSound.pause();eatSound.currentTime=0;eatSound.play().catch(()=>{})}}}}
function collectCrystals(){for(let i=crystals.length-1;i>=0;i--){const crystal=crystals[i];if(Math.hypot(player.x-crystal.x,player.y-crystal.y)<28){crystalTotal++;localStorage.setItem('snakeCrystals',crystalTotal);$('#crystalCount').textContent=crystalTotal;crystals.splice(i,1);crystals.push(makeCrystal())}}}
function bodyPoints(s){const pts=[],whole=Math.floor(s.visualSegments),fraction=s.visualSegments-whole;for(let i=0;i<whole;i++){const p=s.trail[Math.min(s.trail.length-1,8+i*9)];if(p)pts.push(p)}if(fraction>0&&s.trail.length){const a=s.trail[Math.min(s.trail.length-1,8+Math.max(0,whole-1)*9)],b=s.trail[Math.min(s.trail.length-1,8+whole*9)];if(a&&b)pts.push({x:a.x+(b.x-a.x)*fraction,y:a.y+(b.y-a.y)*fraction})}return pts}
function dropExperience(s){const total=Math.max(0,Math.floor(s.score)),shape=[{x:s.x,y:s.y},...bodyPoints(s)];if(!total||!shape.length)return;const count=Math.min(160,Math.max(1,Math.ceil(total/25))),base=Math.floor(total/count),extra=total-base*count;for(let i=0;i<count;i++){const p=shape[Math.round(i*(shape.length-1)/Math.max(1,count-1))],o=makeOrb(p.x+rnd(-7,7),p.y+rnd(-7,7));o.size=2;o.radius=8;o.value=base+(i<extra?1:0);o.color=s.color;orbs.push(o)}}
function collisions(){const snakes=[player,...bots].filter(s=>s?.alive),cell=70,grid=new Map(),key=(x,y)=>`${Math.floor(x/cell)},${Math.floor(y/cell)}`;for(const owner of snakes){const body=bodyPoints(owner);for(let i=1;i<body.length;i++){const p=body[i],k=key(p.x,p.y);if(!grid.has(k))grid.set(k,[]);grid.get(k).push({p,owner})}}for(const s of snakes){if(s.shield>0)continue;const cx=Math.floor(s.x/cell),cy=Math.floor(s.y/cell);outer:for(let x=cx-1;x<=cx+1;x++)for(let y=cy-1;y<=cy+1;y++)for(const hit of grid.get(`${x},${y}`)||[]){if(hit.owner!==s&&hit.owner.shield<=0&&Math.hypot(s.x-hit.p.x,s.y-hit.p.y)<17){kill(s);break outer}}}for(let i=0;i<snakes.length;i++)for(let j=i+1;j<snakes.length;j++){const a=snakes[i],b=snakes[j];if(a.alive&&b.alive&&a.shield<=0&&b.shield<=0&&dist(a,b)<22){kill(a);kill(b)}}}
function kill(s){if(!s.alive)return;s.alive=false;if(onlineSocket)dropExperience(s);else{const shape=[{x:s.x,y:s.y},...bodyPoints(s)],drops=Math.min(120,Math.floor(s.score*.5/50));for(let i=0;i<drops;i++){const position=drops===1?0:Math.round(i*(shape.length-1)/(drops-1)),p=shape[Math.min(shape.length-1,position)];orbs.push(makeOrb(p.x+rnd(-2,2),p.y+rnd(-2,2),true))}}if(s.isBot){const idx=bots.indexOf(s);respawns.push({at:performance.now()+5000,idx})}else gameOver()}
function gameOver(){running=false;music.pause();const score=Math.floor(player.score),best=Math.max(score,Number(localStorage.getItem('snakeBestScore')||0));localStorage.setItem('snakeBestScore',best);$('#resultScore').textContent=score+' очков';$('#resultOverlay').classList.remove('hidden')}
function updateRespawns(){const now=performance.now();for(let i=respawns.length-1;i>=0;i--)if(now>=respawns[i].at){const r=respawns.splice(i,1)[0];bots[r.idx]=makeSnake(botNames[Math.floor(Math.random()*botNames.length)],`hsl(${Math.floor(Math.random()*360)} 78% 56%)`,true)}}
function update(dt){updateSnake(player,dt);collectCrystals();if(!onlineSocket){bots.forEach(s=>updateSnake(s,dt));collisions();updateRespawns()}networkClock-=dt;if(onlineSocket?.readyState===WebSocket.OPEN&&networkClock<=0){networkClock=.05;onlineSocket.send(JSON.stringify({type:'input',angle:player.targetAngle,boost}))}$('#score').textContent=Math.floor(player.score);leaderClock-=dt;if(leaderClock<=0){leaderClock=.25;drawLeaderboard()}}
function cam(){return{x:player.x-innerWidth/2,y:player.y-innerHeight/2}}function worldToScreen(p,c){return{x:p.x-c.x,y:p.y-c.y}}
function drawGrid(c){ctx.fillStyle='#24272c';ctx.fillRect(0,0,innerWidth,innerHeight);ctx.strokeStyle='#30343a';ctx.lineWidth=1;const size=70,h=60;for(let row=Math.floor(c.y/h)-2;row<(c.y+innerHeight)/h+2;row++)for(let col=Math.floor(c.x/size)-2;col<(c.x+innerWidth)/size+2;col++){const x=col*size-(row%2?size/2:0)-c.x,y=row*h-c.y;ctx.beginPath();for(let k=0;k<6;k++){const a=Math.PI/3*k;ctx.lineTo(x+32*Math.cos(a),y+32*Math.sin(a))}ctx.closePath();ctx.stroke()}ctx.save();ctx.strokeStyle='#ef3047';ctx.shadowColor='#ef3047';ctx.shadowBlur=16;ctx.lineWidth=9;ctx.beginPath();ctx.arc(WORLD_CENTER-c.x,WORLD_CENTER-c.y,WORLD_RADIUS,0,Math.PI*2);ctx.stroke();ctx.restore()}
function drawOrb(o,c){const p=worldToScreen(o,c);if(p.x<-30||p.y<-30||p.x>innerWidth+30||p.y>innerHeight+30)return;ctx.save();ctx.shadowColor=o.color;ctx.shadowBlur=18;ctx.fillStyle=o.color;ctx.beginPath();ctx.arc(p.x,p.y,o.radius,0,Math.PI*2);ctx.fill();ctx.restore()}
function drawCrystal(crystal,c){const p=worldToScreen(crystal,c);if(p.x<-40||p.y<-40||p.x>innerWidth+40||p.y>innerHeight+40)return;const pulse=1+Math.sin(performance.now()*.005+crystal.phase)*.12;ctx.save();ctx.translate(p.x,p.y);ctx.scale(pulse,pulse);ctx.shadowColor='#47f4ff';ctx.shadowBlur=24;ctx.fillStyle='#58eaff';ctx.strokeStyle='#d8ffff';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,-14);ctx.lineTo(11,0);ctx.lineTo(0,16);ctx.lineTo(-11,0);ctx.closePath();ctx.fill();ctx.stroke();ctx.restore()}
function smoothPath(points,c){if(points.length<2)return;const p0=worldToScreen(points[0],c);ctx.beginPath();ctx.moveTo(p0.x,p0.y);for(let i=1;i<points.length-1;i++){const p=worldToScreen(points[i],c),n=worldToScreen(points[i+1],c);ctx.quadraticCurveTo(p.x,p.y,(p.x+n.x)/2,(p.y+n.y)/2)}const end=worldToScreen(points[points.length-1],c);ctx.lineTo(end.x,end.y)}
function drawSnake(s,c){if(!s.alive)return;const rawPts=bodyPoints(s),h=worldToScreen(s,c),now=performance.now(),thickness=29+Math.min(18,Math.max(0,s.visualSegments-3)*.2),wave=Math.min(2.2,1+rawPts.length*.012),pts=rawPts.map((p,i)=>{const before=rawPts[Math.max(0,i-1)]||p,after=rawPts[Math.min(rawPts.length-1,i+1)]||p,dx=after.x-before.x,dy=after.y-before.y,d=Math.hypot(dx,dy)||1,offset=Math.sin(now*.003+i*.62+s.wiggle)*wave;return{x:p.x-dy/d*offset,y:p.y+dx/d*offset}});ctx.save();if(s.shield>0)ctx.globalAlpha=.35+.25*Math.sin(now/75);ctx.lineCap='round';ctx.lineJoin='round';ctx.shadowColor=s.color;ctx.shadowBlur=9;ctx.strokeStyle=s.color;ctx.lineWidth=thickness+Math.sin(now/430+s.wiggle)*.6;smoothPath([{x:s.x,y:s.y},...pts],c);ctx.stroke();ctx.shadowBlur=0;ctx.globalAlpha*=.2;ctx.strokeStyle='#fff';ctx.lineWidth=Math.max(4.5,thickness*.16);smoothPath([{x:s.x-5*Math.sin(s.angle),y:s.y+5*Math.cos(s.angle)},...pts.map(p=>({x:p.x-4*Math.sin(s.angle),y:p.y+4*Math.cos(s.angle)}))],c);ctx.stroke();ctx.globalAlpha=s.shield>0?.35+.25*Math.sin(now/75):1;ctx.fillStyle=s.color;ctx.save();ctx.translate(h.x,h.y);ctx.rotate(s.angle);ctx.beginPath();ctx.ellipse(2,0,thickness*.69+Math.sin(now/430+s.wiggle)*.45,thickness*.57,0,0,Math.PI*2);ctx.fill();ctx.restore();const fx=Math.cos(s.angle),fy=Math.sin(s.angle),sx=-fy,sy=fx,blink=Math.sin(now/850+s.wiggle)>0.985?.18:1,eyeForward=thickness*.27,eyeSide=thickness*.24,eyeSize=Math.min(7,thickness*.19);for(const side of [-1,1]){const ex=h.x+fx*eyeForward+sx*side*eyeSide,ey=h.y+fy*eyeForward+sy*side*eyeSide;ctx.save();ctx.translate(ex,ey);ctx.rotate(s.angle);ctx.scale(1,blink);ctx.fillStyle='#fff';ctx.beginPath();ctx.ellipse(0,0,eyeSize,eyeSize*.9,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#111';ctx.beginPath();ctx.arc(eyeSize*.36,0,eyeSize*.43,0,Math.PI*2);ctx.fill();ctx.restore()}if((now/1000+s.wiggle)%4<.16){const tx=h.x+fx*(thickness*.8),ty=h.y+fy*(thickness*.8);ctx.strokeStyle='#ff6b91';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(h.x+fx*(thickness*.5),h.y+fy*(thickness*.5));ctx.lineTo(tx,ty);ctx.lineTo(tx+fx*5+sx*3,ty+fy*5+sy*3);ctx.moveTo(tx,ty);ctx.lineTo(tx+fx*5-sx*3,ty+fy*5-sy*3);ctx.stroke()}ctx.font='14px system-ui';ctx.textAlign='center';ctx.lineWidth=3;ctx.strokeStyle='rgba(0,0,0,.75)';ctx.strokeText(s.name,h.x,h.y-thickness*.72-9);ctx.fillStyle='#fff';ctx.fillText(s.name,h.x,h.y-thickness*.72-9);ctx.restore()}
function drawSkin(s,c){if(!s.alive)return;const head=worldToScreen(s,c);if(head.x<-450||head.y<-450||head.x>innerWidth+450||head.y>innerHeight+450)return;const pts=bodyPoints(s),base=29+Math.min(18,Math.max(0,s.visualSegments-3)*.2);ctx.save();ctx.globalAlpha=s.shield>0?.22:.42;for(let i=0;i<pts.length;i+=2){const p=worldToScreen(pts[i],c),before=pts[Math.max(0,i-1)]||pts[i],after=pts[Math.min(pts.length-1,i+1)]||pts[i],a=Math.atan2(after.y-before.y,after.x-before.x),tail=1-i/Math.max(1,pts.length),r=base*(.23+.18*tail);if(p.x<-40||p.y<-40||p.x>innerWidth+40||p.y>innerHeight+40)continue;ctx.save();ctx.translate(p.x,p.y);ctx.rotate(a);ctx.fillStyle=i%4===0?'rgba(255,255,255,.48)':'rgba(10,10,16,.42)';ctx.beginPath();ctx.ellipse(0,(i%4<2?-1:1)*base*.18,r,r*.48,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle='rgba(255,255,255,.18)';ctx.lineWidth=1;ctx.stroke();ctx.restore()}ctx.globalAlpha=.22;ctx.strokeStyle='#fff';ctx.lineWidth=Math.max(2,base*.09);smoothPath([{x:s.x,y:s.y},...pts.slice(0,Math.ceil(pts.length*.82))],c);ctx.stroke();ctx.restore()}
function draw(){const c=cam();drawGrid(c);orbs.forEach(o=>drawOrb(o,c));crystals.forEach(crystal=>drawCrystal(crystal,c));bots.forEach(s=>{drawSnake(s,c);drawSkin(s,c)});drawSnake(player,c);drawSkin(player,c);drawMini()}
function drawMini(){const w=mini.width,h=mini.height;mctx.clearRect(0,0,w,h);mctx.fillStyle='#444951';mctx.fillRect(0,0,w,h);mctx.strokeStyle='#ef3047';mctx.lineWidth=4;mctx.beginPath();mctx.arc(w/2,h/2,w/2-5,0,Math.PI*2);mctx.stroke();mctx.fillStyle=player.color;mctx.shadowColor=player.color;mctx.shadowBlur=8;mctx.beginPath();mctx.arc(player.x/WORLD*w,player.y/WORLD*h,5,0,Math.PI*2);mctx.fill();mctx.shadowBlur=0}
function drawLeaderboard(){const all=[player,...bots].filter(s=>s?.alive).sort((a,b)=>b.score-a.score),top=all.slice(0,10),place=all.indexOf(player)+1;$('#leaderList').innerHTML=top.map(s=>`<li class="${s===player?'me':''}">${s.name} — ${Math.floor(s.score)}</li>`).join('');$('#playerPlace').textContent=place>10?`${place}. ${player.name} — ${Math.floor(player.score)}`:''}
function loop(now){if(!running)return;const dt=Math.min(.034,(now-last)/1000);last=now;if(!paused){update(dt);draw()}requestAnimationFrame(loop)}
